### PR TITLE
Added cat and monkey

### PR DESCRIPTION
**Pull request by anshks**

### CODE REVIEW

**Review by jrtechs — CHANGES_REQUESTED** [review]
Can you add tic marks to the ascii mark so it leads up to the quote.

welcome

**Comment by anshks** [comment]
@jrtechs i have added marks.

**Review by jrtechs — CHANGES_REQUESTED** [review]
Can you add tic marks above the cat so it leads up to the quote bubble.

**Comment by jrtechs** [comment]
stale PR

**Pull request closed without merging**
