### PR TITLE
Add windows logo ascii art

### PR DESCRIPTION
**Pull request by dukkee**

### CODE REVIEW

**Review by jrtechs — CHANGES_REQUESTED** [review]
Can you add the backslashes to this so it can lead up to the quote bubble

**Comment by dukkee** [comment]
@jrtechs fixed

**Review by jrtechs — CHANGES_REQUESTED** [review]
Almost, can the tic marks lead up to the quote bubble like a speech box.

welcome

**Comment by jrtechs** [comment]
Stale PR.

**Pull request closed without merging**
